### ISSUE TITLE
Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by sarg** [Wilfred/elisp-refs#25]
In Erefs mode when I press `RET` on `Line:` or on an empty line the following error occurs:
```
funcall-interactively: Wrong type argument: number-or-marker-p, nil
```
The reason is that `elisp-refs-visit-match` assumes that the text has always properties attached. 
```lisp
(unindent (get-text-property (point) 'elisp-refs-unindented))
(target-offset (+ column-offset unindent))
```
Maybe this will do the trick:
```lisp
(target-offset (if unindent (+ column-offset unindent)))
```

**Comment by Wilfred** [comment]
Thank you :)
