### ISSUE TITLE
elisp-refs-function and elisp-refs-macro returns the same matches

### ISSUE THREAD

**Issue by calancha** [Wilfred/elisp-refs#4]
For instance,
(elisp-refs-function 'cl-loop)
=>
Found 70 references to function cl-loop in 16 files.

(elisp-refs-macro 'cl-loop)
=>
Found 70 references to macro cl-loop in 16 files.

Do do you need two functions?
Why not to define `elisp-refs-function-or-macro'?

What about to make `elisp-refs-function' just
returns matches for actual functions, i.e., to not return
matches for macro calls?

**Comment by Wilfred** [comment]
`elisp-refs-function` and `elisp-refs-macro` are not equivalent. `elisp-refs-function` will look for s-expressions like `(funcall 'foo)`, but `elisp-refs-macro` will not. They will also offer different completion options when called interactively.

`elisp-refs-function` does only return matches for functions when you call it with a function name. Why were you calling `elisp-refs-function` with `cl-loop`?

I suppose we could error in this case, if you think that's helpful.
